'''

Wir haben nun gesehen wie wir (mehrere) Fehler abfangen können. 
Allerdings müsste man öfters auch selbst Fehler auslösen, damit
keine Fehlerhaften Eingaben getätigt werden können!

'''


def main():
    pass


if __name__ == "__main__":
    main()